import { readFile, writeFile, mkdir } from 'node:fs/promises';
import sharp from 'sharp';
const c = JSON.parse(await readFile(new URL('../content.json', import.meta.url), 'utf8'));
const root = new URL('../', import.meta.url);
const out = (name, value) => writeFile(new URL(name, root), value);
const e = value => String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const base = new URL(c.site.url.endsWith('/') ? c.site.url : c.site.url + '/');
if (!['https:', 'http:'].includes(base.protocol)) throw new Error('site.url must be an absolute HTTP(S) URL');
const url = path => new URL(path, base).href;
const arrow = '<span aria-hidden="true">↗</span>';
const link = (href, label, cls='text-link') => `<a class="${cls}" href="${e(href)}">${e(label)} ${arrow}</a>`;
const eyebrow = text => `<p class="eyebrow">${e(text)}</p>`;
const tags = items => `<ul class="tags">${items.map(t=>`<li>${e(t)}</li>`).join('')}</ul>`;
const stats = () => `<dl class="stats">${c.stats.map(s=>`<div><dt>${e(s.label)}</dt><dd>${e(s.value)}</dd></div>`).join('')}</dl>`;
const globe = () => `<svg class="globe" viewBox="0 0 500 460" aria-hidden="true" focusable="false"><defs><radialGradient id="globe-fill" cx="30%" cy="30%"><stop stop-color="#eeeaff"/><stop offset="1" stop-color="#c4b5ed"/></radialGradient><clipPath id="globe-clip"><circle cx="250" cy="224" r="158"/></clipPath></defs><ellipse cx="250" cy="240" rx="229" ry="72" fill="none" stroke="#659781" stroke-width="1" transform="rotate(-28 250 240)"/><circle cx="250" cy="224" r="158" fill="url(#globe-fill)" stroke="#8877b4"/><g clip-path="url(#globe-clip)" fill="none" stroke="#8d7bb8" stroke-width="1"><ellipse cx="250" cy="224" rx="108" ry="158"/><ellipse cx="250" cy="224" rx="44" ry="158"/><ellipse cx="250" cy="224" rx="158" ry="110"/><ellipse cx="250" cy="224" rx="158" ry="49"/><path d="M92 224h316M250 66v316"/></g><path d="M49 284c43 14 129 1 212-44s153-96 166-129" fill="none" stroke="#245943" stroke-width="2"/><g fill="#205d43" stroke="#f4fff8" stroke-width="5"><circle cx="130" cy="286" r="9"/><circle cx="369" cy="159" r="9"/><circle cx="293" cy="348" r="7"/></g><g fill="#5a427c"><path d="M415 302v24m-12-12h24M76 130v16m-8-8h16" stroke="#5a427c" stroke-width="2"/></g></svg>`;
const tree = `<svg viewBox="0 0 360 220" aria-hidden="true" focusable="false"><g stroke="#97b8a6" fill="none"><path d="M0 180L180 80l180 100M0 140l180 100 180-100M60 210V10m80 210V0m80 220V0m80 210V10" opacity=".45"/><path d="M0 60l360 140M0 10l360 140" opacity=".25"/></g><g stroke="#226344" stroke-width="3"><path d="M180 168V95m-90 76v-44m185 39v-56"/></g><g fill="#7fc496" stroke="#226344" stroke-width="1.5"><path d="M180 35c-16 0-31 16-29 30-25 5-30 39-7 49 12 5 26 0 36-5 14 9 33 10 43-2 16-18 7-41-13-46-1-16-16-26-30-26Z"/><path d="M90 80c-13 0-20 10-20 20-19 6-18 30-1 35 8 3 15 1 21-3 20 12 42-6 29-24-2-5-7-9-12-9 0-10-8-19-17-19Z"/><path d="M275 62c-13 0-20 10-20 20-19 6-18 30-1 35 8 3 15 1 21-3 20 12 42-6 29-24-2-5-7-9-12-9 0-10-8-19-17-19Z"/></g></svg>`;
const wallet = `<svg viewBox="0 0 360 220" aria-hidden="true" focusable="false"><g fill="none" stroke="#a18fbf"><circle cx="180" cy="110" r="95"/><ellipse cx="180" cy="110" rx="150" ry="62" transform="rotate(-20 180 110)"/></g><rect x="92" y="57" width="176" height="116" rx="17" fill="#f6f1ff" stroke="#655080" stroke-width="2"/><path d="M108 58V45h126v13" fill="#c7b4e6" stroke="#655080" stroke-width="2"/><rect x="222" y="93" width="61" height="42" rx="9" fill="#b5d9c2" stroke="#3e6e54" stroke-width="2"/><circle cx="240" cy="114" r="4" fill="#3e6e54"/><path d="M118 87h56m-56 13h36" stroke="#a18fbf" stroke-width="3" stroke-linecap="round"/><g fill="#4d755c"><circle cx="54" cy="137" r="6"/><circle cx="307" cy="74" r="6"/></g></svg>`;
function visual(p) { return `<div class="program-visual ${p.id}">${eyebrow(p.visualLabel)}<p class="visual-title">${e(p.visualTitle)}</p>${p.id==='greensight'?tree:wallet}<span class="visual-caption">${e(p.visualNote)}</span></div>`; }
function collaborators(full=false) {const s=c.collaborators;return `<section class="collaborators ${full?'section':''}" aria-labelledby="collab-title">${eyebrow(s.label)}${full?`<h2 id="collab-title">${e(s.title)}</h2><p class="section-intro">${e(s.intro)}</p>`:`<h2 id="collab-title" class="sr-only">${e(s.title)}</h2>`}<div class="collaborator-grid">${s.items.map(p=>`<div class="collaborator"><span class="partner-mark" aria-hidden="true">${e(p.mark)}</span><div><h3>${e(p.name)}</h3><p>${e(p.detail)}</p></div></div>`).join('')}</div></section>`;}
function contact() {const s=c.contact;return `<section class="contact" id="contact" aria-labelledby="contact-title"><div>${eyebrow(s.eyebrow)}<h2 id="contact-title">${e(s.title)}</h2><p>${e(s.intro)}</p></div><div class="contact-actions">${link('mailto:'+c.site.email,c.ui.email,'button primary')}${link(c.site.instagram.url,c.contact.instagramLabel)}<a class="email-address" href="mailto:${e(c.site.email)}">${e(c.site.email)}</a></div></section>`;}
function founders() {return `<section class="section" id="founders" aria-labelledby="founder-title">${eyebrow(c.about.founderLabel)}<h2 id="founder-title">${e(c.about.founderTitle)}</h2><p class="section-intro">${e(c.about.founderIntro)}</p><div class="founder-grid">${c.about.founders.map((f,i)=>`<article class="founder"><img src="assets/founder-${i}.webp" alt="${e(f.name)}" width="640" height="760" loading="lazy" decoding="async" style="object-position:${e(f.position)}"><div><h3>${e(f.name)}</h3><p>${e(c.about.founderRole)}</p></div></article>`).join('')}</div></section>`;}
function pageHeader(s) {return `<section class="page-heading">${eyebrow(s.eyebrow)}<h1>${e(s.headline)}</h1><p class="lead">${e(s.intro)}</p></section>`;}
function home() {return `<section class="hero"><div class="hero-copy">${eyebrow(c.home.eyebrow)}<h1>${c.home.headline.map((l,i)=>`<span${i===1?' class="purple"':''}>${e(l)}</span>`).join('')}</h1><p class="lead">${e(c.home.intro)}</p><div class="hero-metrics">${stats()}</div><div class="button-group">${link('projects.html',c.ui.work,'button primary')}${link('about.html',c.ui.story,'button secondary')}</div></div><div class="network-art">${eyebrow(c.home.networkLabel)}${globe()}<div class="network-note"><span class="note-icon" aria-hidden="true">&lt;/&gt;</span><span>${e(c.home.networkNote)}</span></div></div></section>${collaborators()}<section class="section" aria-labelledby="work-title"><div class="section-heading"><div>${eyebrow(c.home.workLabel)}<h2 id="work-title">${e(c.home.workTitle)}</h2></div><p>${e(c.home.workIntro)}</p></div><div class="work-grid">${c.programs.items.map(p=>`<article class="work-card">${visual(p)}<div class="work-copy">${eyebrow(p.category)}<h3>${e(p.name)}</h3><p>${e(p.summary)}</p>${tags(p.tags)}${link('projects.html#'+p.id,c.ui.programLink)}</div></article>`).join('')}</div></section><section class="story-preview"><div class="story-symbol" aria-hidden="true">{<span>us</span>}</div><div>${eyebrow(c.home.storyLabel)}<h2>${e(c.home.storyTitle)}</h2><p>${e(c.home.storyText)}</p>${link('about.html',c.ui.story)}</div></section>${contact()}`;}
function about(){return `${pageHeader(c.about)}<div class="story-layout"><aside class="story-aside">${globe()}${stats()}</aside><div class="story-chapters">${c.about.chapters.map(s=>`<section>${eyebrow(s.label)}<h2>${e(s.title)}</h2><p>${e(s.text)}</p>${s.more?`<p>${e(s.more)}</p>`:''}</section>`).join('')}</div></div>${founders()}${contact()}`;}
function programs(){return `${pageHeader(c.programs)}<div class="program-stories">${c.programs.items.map(p=>`<article class="program-story" id="${p.id}">${visual(p)}<div class="program-body">${eyebrow(p.category)}<h2>${e(p.name)}</h2><h3>${e(p.headline)}</h3><p>${e(p.detail)}</p>${tags(p.tags)}<div class="outcome">${eyebrow(p.resultLabel)}<p>${e(p.outcome)}</p></div>${p.duration?`<p class="duration"><strong>${e(p.duration)}</strong> ${e(p.durationLabel)}</p>`:''}</div></article>`).join('')}</div>${collaborators(true)}${contact()}`;}
function render({file,title,body,canonical=file,noindex=false}) {
 const canonicalUrl=url(canonical);
 const schema={'@context':'https://schema.org','@type':'Organization',name:c.site.name,url:base.href,description:c.site.description,email:c.site.email,logo:url('assets/logo.webp'),sameAs:[c.site.instagram.url],founder:c.about.founders.map(f=>({'@type':'Person',name:f.name}))};
 return `<!doctype html>\n<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f7faf6"><title>${e(title)}</title><meta name="description" content="${e(c.site.description)}"><link rel="canonical" href="${e(canonicalUrl)}">${noindex?'<meta name="robots" content="noindex,follow">':''}<meta property="og:type" content="website"><meta property="og:site_name" content="${e(c.site.name)}"><meta property="og:title" content="${e(title)}"><meta property="og:description" content="${e(c.site.description)}"><meta property="og:url" content="${e(canonicalUrl)}"><meta property="og:image" content="${e(url('assets/og.png'))}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="${e(c.ui.socialAlt)}"><meta name="twitter:card" content="summary_large_image"><link rel="icon" href="${noindex&&file==='404.html'?e(url('assets/favicon.png')):'assets/favicon.png'}" type="image/png"><link rel="apple-touch-icon" href="${file==='404.html'?e(url('assets/apple-touch-icon.png')):'assets/apple-touch-icon.png'}"><link rel="stylesheet" href="${file==='404.html'?e(url('styles.css')):'styles.css'}"><script defer src="${file==='404.html'?e(url('script.js')):'script.js'}"></script><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script></head><body><a class="skip-link" href="#main">${e(c.ui.skip)}</a><header class="header"><div class="header-inner"><a class="brand" href="index.html"><img src="assets/logo.webp" alt="" width="44" height="44"><span>${e(c.site.name)}</span></a><button class="menu-button" type="button" aria-expanded="false" aria-controls="main-nav" hidden>${e(c.ui.menu)} <span aria-hidden="true">☰</span></button><nav id="main-nav" aria-label="${e(c.ui.navigation)}">${c.nav.map(n=>`<a href="${e(n.href)}"${canonical===n.href?' aria-current="page"':''}>${e(n.label)}</a>`).join('')}${link('#contact',c.ui.contact,'nav-contact')}</nav></div></header><main id="main" tabindex="-1" class="wrap">${body}</main><footer class="footer"><div class="wrap footer-inner"><div><a class="brand" href="index.html">${e(c.site.name)}</a><p>${e(c.site.footer)}</p></div><nav aria-label="${e(c.ui.footerNavigation)}">${link('mission.html',c.mission.eyebrow)}${link('about.html#founders',c.ui.founders)}${link(c.site.instagram.url,c.site.instagram.label)}</nav><p class="copyright">© ${new Date().getFullYear()} ${e(c.site.copyright)}</p></div></footer></body></html>\n`;
}
await mkdir(new URL('assets/',root),{recursive:true});
await sharp(new URL(c.site.logo,root).pathname).resize(104,104).webp({quality:85}).toFile(new URL('assets/logo.webp',root).pathname);
for (const [i,f] of c.about.founders.entries()) await sharp(new URL(f.image,root).pathname).rotate().resize({width:640,height:900,fit:'inside',withoutEnlargement:true}).webp({quality:82}).toFile(new URL(`assets/founder-${i}.webp`,root).pathname);
for (const [name,size] of [['favicon.png',48],['apple-touch-icon.png',180]]) await sharp(new URL(c.site.logo,root).pathname).resize(size,size).png().toFile(new URL('assets/'+name,root).pathname);
const og=`<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#f1f7f0"/><circle cx="1050" cy="155" r="280" fill="#e6def8"/><circle cx="1090" cy="350" r="200" fill="none" stroke="#a998c4" stroke-width="2"/><g font-family="Arial, sans-serif" fill="#174b36"><text x="75" y="96" font-size="30" font-weight="700">${e(c.site.name)}</text><text x="75" y="217" font-size="76" font-weight="700">${e(c.home.headline[0])}</text><text x="75" y="303" font-size="76" font-weight="700" fill="#65458a">${e(c.home.headline[1])} ${e(c.home.headline[2])}</text><path d="M75 370H1125" stroke="#bdccbe"/><text x="75" y="457" font-size="58" font-weight="700">${e(c.stats[0].value)}</text><text x="300" y="457" font-size="58" font-weight="700">${e(c.stats[1].value)}</text><text x="75" y="497" font-size="25">${e(c.stats[0].label)}</text><text x="300" y="497" font-size="25">${e(c.stats[1].label)}</text><text x="75" y="580" font-size="24">${e(c.site.footer)}</text></g></svg>`;
await sharp(Buffer.from(og)).png().toFile(new URL('assets/og.png',root).pathname);
const pages=[{file:'index.html',title:c.home.title,body:home()},{file:'about.html',title:c.about.title,body:about()},{file:'projects.html',title:c.programs.title,body:programs()},{file:'mission.html',title:c.mission.title,body:`${pageHeader(c.mission)}<section class="mission-body"><p>${e(c.mission.body)}</p>${stats()}${link('projects.html',c.ui.work,'button primary')}</section>${contact()}`},{file:'meetings.html',canonical:'about.html',noindex:true,title:c.about.title,body:about()},{file:'team.html',canonical:'about.html',noindex:true,title:c.about.title,body:about()},{file:'404.html',noindex:true,title:c.notFound.title,body:`${pageHeader(c.notFound)}${link(base.href,c.ui.home,'button primary')}${contact()}`}];
for(const p of pages) {let html=render(p); if(p.file==='404.html') html=html.replace(/(href|src)="(index\.html|about\.html(?:#founders)?|projects\.html|mission\.html|assets\/logo.webp)"/g,(_,attr,path)=>`${attr}="${e(url(path))}"`); await out(p.file,html);}
await out('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.filter(p=>!p.noindex).map(p=>`<url><loc>${e(url(p.file))}</loc></url>`).join('')}</urlset>\n`);
await out('robots.txt',`User-agent: *\nAllow: /\n\nSitemap: ${url('sitemap.xml')}\n`);
console.log(`Built ${pages.length} static pages and optimized assets. Canonical base: ${base.href}`);
